### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by Pep00000001** [iliasam/uProbe#1]
Im using IAR v7502-10505 
loaded the project file project.eww - no changes to code
hit make, got missing file error "startup_stm32f303xc" in system folder
Grabbed the STM32F30x_StdPeriph_Driver from ST and put the file into the project  /system folder now the build log has 182 errors 

how to fix ?

**Comment by iliasam** [comment]
I added my startup_stm32f303xc.s file to the repository, try to update your sources ftom Git.
#https://github.com/iliasam/uProbe/commit/71181a42fabd19d7c2ea7975eda7543e71634ebe

**Comment by Pep00000001** [comment]
That fixed it. Thanks!
